Updated to Xcode Version 7.0 beta 6 (7A192o)
Fixed one test failure in Random.swift:shuffle:

fatal error: swapping a location with itself is not supported